name: starter_toolkit

description: "Mobile application for starter"

publish_to: 'none'

version: 4.0.0

resolution: workspace

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  auto_route:
  collection:
  dio:
  equatable:
  firebase_crashlytics:
  flutter_bloc:
  flutter_form_builder:
  freezed_annotation:
  http_parser:
  image_picker:
  intl:
  intl_utils:
  mask_text_input_formatter:
  permission_handler:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  json_serializable:

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  main_locale: en
  class_name: ToolkitLocalizer
  output_dir: lib/l10n/generated
