name: starter_lints
description: Custom lint rules for flutter_starter project

publish_to: 'none'

version: 3.0.0

resolution: workspace

environment:
  sdk: ^3.12.0

dependencies:
  analyzer:
  custom_lint_builder:
